[partition]
boot = "/dev/sda1"
swap = "/dev/sda2"
root = "/dev/sda3"
label = "archlinux"

[network]
reflector = false
mirrors = ["https://mirrors.ustc.edu.cn/archlinux/$repo/os/$arch"]

[os]
packages = [
  "base",
  "base-devel",
  "linux",
  "linux-firmware",
  "btrfs-progs",
  "networkmanager",
  "vim ",
  "sudo",
  "git",
  "fish",
  "amd-ucode",      # amd-ucode or intel-ucode
  "grub",
  "efibootmgr",
  "os-prober",
  "alacritty",
  "rofi",
  "i3",
  "sddm",
  "fcitx5",
]
enabled_services = ["NetworkManager.service", "sddm.service"]
hostname = "archlinux"
timezone = "Asia/Shanghai"
locale = ["en_US.UTF-8 UTF-8", "zh_CN.UTF-8 UTF-8"]
lang = "en_US.UTF-8"

[user]
name = "admin"
shell = "fish"

[pacman]
multilib = true
archlinuxcn = true

[grub]
bootloader_id = "GRUB"
disable_os_prober = false
